"""empty message

Revision ID: 0ef8c485f28a
Revises: c5be277a97cc
Create Date: 2024-02-17 17:57:52.640082

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ef8c485f28a'
down_revision = 'c5be277a97cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('_password', sa.Text(), nullable=False))
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_index('ix_user_username')
        batch_op.drop_column('password')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=128), nullable=True))
        batch_op.create_index('ix_user_username', ['username'], unique=True)
        batch_op.alter_column('role',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('_password')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
